# YOLOv10 仪表检测模型配置文件
# 配置训练参数、数据增强、模型设置等

# 模型配置
model: 'yolov10n.pt'  # YOLOv10 nano模型，可选：yolov10n.pt, yolov10s.pt, yolov10m.pt, yolov10l.pt, yolov10x.pt

# 训练基本参数
epochs: 150              # 训练轮数
batch_size: 16           # 批大小（根据GPU内存调整）
image_size: 640          # 输入图像大小
learning_rate: 0.01      # 初始学习率
weight_decay: 0.0005     # 权重衰减
momentum: 0.937          # SGD动量
patience: 50             # 早停耐心值
save_period: 10          # 模型保存间隔
experiment_name: 'meter_detection_v1'  # 实验名称

# 设备和性能配置
device: 'mps'            # Apple芯片使用MPS加速，也可以使用'cpu'
workers: 4               # 数据加载器工作进程数（Apple芯片建议减少）
seed: 42                 # 随机种子
cos_lr: false            # 是否使用余弦学习率调度
close_mosaic: 10         # 关闭mosaic增强的epoch数
amp: true                # 自动混合精度训练

# 数据增强配置
augmentation:
  # 颜色空间增强
  hsv_h: 0.015           # 色调增强范围
  hsv_s: 0.7             # 饱和度增强范围
  hsv_v: 0.4             # 亮度增强范围
  
  # 几何变换增强
  degrees: 5.0           # 旋转角度范围（度）
  translate: 0.1         # 平移范围（图像尺寸的比例）
  scale: 0.5             # 缩放范围
  shear: 2.0             # 剪切角度范围（度）
  perspective: 0.0       # 透视变换概率
  
  # 翻转增强
  flipud: 0.0            # 上下翻转概率
  fliplr: 0.5            # 左右翻转概率
  
  # 混合增强
  mosaic: 1.0            # Mosaic增强概率
  mixup: 0.1             # MixUp增强概率
  copy_paste: 0.1        # Copy-Paste增强概率

# 验证和评估配置
validation:
  conf_threshold: 0.25   # 置信度阈值
  iou_threshold: 0.45    # NMS IoU阈值
  max_det: 300           # 最大检测数量

# 损失函数权重
loss_weights:
  box: 7.5               # 边界框损失权重
  cls: 0.5               # 分类损失权重
  dfl: 1.5               # 分布损失权重

# 优化器配置
optimizer:
  type: 'AdamW'          # 优化器类型：SGD, Adam, AdamW
  lr0: 0.01              # 初始学习率
  lrf: 0.01              # 最终学习率（学习率衰减因子）
  weight_decay: 0.0005   # 权重衰减

# 学习率调度器
lr_scheduler:
  type: 'linear'         # 学习率调度类型：linear, cosine, polynomial
  warmup_epochs: 3       # 预热轮数
  warmup_momentum: 0.8   # 预热动量
  warmup_bias_lr: 0.1    # 预热偏置学习率

# 模型导出配置
export:
  formats: ['onnx', 'torchscript']  # 导出格式
  optimize: true         # 是否优化导出模型
  half: false            # 是否使用FP16
  int8: false            # 是否使用INT8量化
  dynamic: false         # 是否支持动态输入尺寸
  simplify: true         # 是否简化ONNX模型

# 日志和可视化配置
logging:
  log_level: 'INFO'      # 日志级别
  save_plots: true       # 是否保存训练图表
  save_predictions: true # 是否保存预测结果
  
# 特定于仪表检测的配置
meter_detection:
  min_meter_size: 32     # 最小仪表尺寸（像素）
  max_meter_size: 800    # 最大仪表尺寸（像素）
  aspect_ratio_range: [0.5, 2.0]  # 宽高比范围
  
# 回调函数配置
callbacks:
  early_stopping:
    enabled: true
    patience: 30
    min_delta: 0.001
  
  model_checkpoint:
    save_best_only: true
    save_weights_only: false
    
  reduce_lr_on_plateau:
    enabled: false
    factor: 0.5
    patience: 10
    min_lr: 1e-6 