amp: true
augmentation:
  copy_paste: 0.0
  degrees: 5.0
  fliplr: 0.0
  flipud: 0.0
  hsv_h: 0.01
  hsv_s: 0.5
  hsv_v: 0.3
  mixup: 0.0
  mosaic: 0.5
  perspective: 0.0
  scale: 0.3
  shear: 2.0
  translate: 0.05
batch_size: 16
close_mosaic: 10
cos_lr: false
device: auto
epochs: 150
experiment_name: digit_detection
image_size: 640
learning_rate: 0.01
model: yolov10n.pt
momentum: 0.937
patience: 50
save_period: 10
seed: 42
train_split: 0.8
weight_decay: 0.0005
workers: 8
